pang_cmfz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('show/', include('pss_show.urls')),
    path('banner/', include('pss_banner.urls')),
    path('user/', include('pss_user.urls')),
    path('article/', include('pss_article.urls')),
    path('album/', include('pss_album.urls')),
    path('rbac/', include('rbac.urls')),
    path('test/', include('pss_test.urls')),
]

pss_show/urls.py
from django.urls import path

from pss_show import views

app_name = "pss_show"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login, name="login"),
    path('getcode/', views.get_code, name="getcode"),
    path('loginlogic/', views.loginlogic, name="loginlogic"),
    path('logOut/', views.logOut, name="logOut"),
]

rbac/urls.py
from django.urls import path
from rbac import views

app_name = "rbac"

urlpatterns = [
    # path('login/', views.login, name="login"),
    # path('check_user/', views.check_user, name="check_user"),

]

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>商品后台管理系统</title>
    <link rel="icon" href="{% static 'img/arrow-up.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'boot/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'boot/css/back.css' %}">
    <link rel="stylesheet" href="{% static 'jqgrid/css/trirand/ui.jqgrid-bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'jqgrid/css/jquery-ui.css' %}">
    <script src="{% static 'boot/js/jquery-2.2.1.min.js' %}"></script>
    <script src="{% static 'boot/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'jqgrid/js/trirand/src/jquery.jqGrid.js' %}"></script>
    <script src="{% static 'jqgrid/js/trirand/i18n/grid.locale-cn.js' %}"></script>
    <script src="{% static 'boot/js/ajaxfileupload.js' %}"></script>
    <script src="{% static 'echarts/echarts.min.js' %}"></script>
    <script src="{% static 'echarts/china.js' %}"></script>
    <script src="{% static 'kindeditor/kindeditor-all-min.js' %}"></script>
    <script src="{% static 'kindeditor/lang/zh-CN.js' %}"></script>

</head>
<script>
    let session_per_list;
    function myfun() {
        session_per_list = $('#session_per_list').text();
        console.log("session  ", session_per_list);
    }

    window.onload = myfun;

    //退出登录的函数
    function logOut() {
        $.ajax({
            url:"{% url 'pss_show:logOut' %}",
            type:"get",
            data:"",
            success:function (resp) {
                location.href = "{% url 'pss_show:login' %}"
            }
        })
    }

</script>
<body>
<span id="session_per_list" style="display: none">{{ per_list }}</span>

<!-- 导航条 -->
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">持明法洲管理系统</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">欢迎：{{ name }}</a></li>
                <li>
                    <a href="#" onclick="logOut()">
                        退出登录
                        <span class="glyphicon glyphicon-log-out"></span>
                    </a>
                </li>

            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<!--栅格系统-->
<div class="container-fluid">
    <div class="row">
        <!--左边-->
        <div class="col-sm-2">
            <!--手风琴-->
            <div class="panel-group" id="accordion">
                <!--用户菜单-->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="panel-title">
                            <a href="#aa" data-toggle="collapse" data-parent="#accordion">
                                <h4>用户管理</h4>
                            </a>
                        </div>
                    </div>
                    <div id="aa" class="panel-collapse collapse">
                        <div class="panel-body">
                            {% for item in request.session.menu_list %}
                                {% if  '/user/' in item.url %}
                                    <ul class="nav nav-pills nav-stacked">
                                        <li><a href="javascript:$('#centerLayout').load('{% static item.html_uri %}')" style="font-weight: bold">{{ item.title }}</a></li>
                                    </ul>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>

                <!--文章管理-->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="panel-title">
                            <a href="#dds" data-toggle="collapse" data-parent="#accordion">
                                <h4>文章管理</h4>
                            </a>
                        </div>
                    </div>
                    <div id="dds" class="panel-collapse collapse ">
                        <div class="panel-body">
                            {% for item in request.session.menu_list %}
                                {% if  '/article/' in item.url %}
                                    <ul class="nav nav-pills nav-stacked">
                                        <li><a href="javascript:$('#centerLayout').load('{% static item.html_uri %}')" style="font-weight: bold">{{ item.title }}</a></li>
                                    </ul>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <!--专辑管理-->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="panel-title">
                            <a href="#dd" data-toggle="collapse" data-parent="#accordion">
                                <h4>专辑管理</h4>
                            </a>
                        </div>
                    </div>
                    <div id="dd" class="panel-collapse collapse ">
                        <div class="panel-body">
                            {% for item in request.session.menu_list %}
                                {% if  '/album/' in item.url %}
                                    <ul class="nav nav-pills nav-stacked">
                                        <li><a href="javascript:$('#centerLayout').load('{% static item.html_uri %}')" style="font-weight: bold">{{ item.title }}</a></li>
                                    </ul>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <!--轮播图管理-->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="panel-title">
                            <a href="#cc" data-toggle="collapse" data-parent="#accordion">
                                <h4>轮播图管理</h4>
                            </a>
                        </div>
                    </div>
                    <div id="cc" class="panel-collapse collapse ">
                        <div class="panel-body">
                            <!--通过load方法加载轮播图管理的页面-->
                             {% for item in request.session.menu_list %}
                                {% if  '/banner/' in item.url %}
                                    <ul class="nav nav-pills nav-stacked">
                                        <li><a href="javascript:$('#centerLayout').load('{% static item.html_uri %}')" style="font-weight: bold">{{ item.title }}</a></li>
                                    </ul>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="panel-title">
                            <a href="#dd" data-toggle="collapse" data-parent="#accordion">
                                <h4>管理员管理</h4>
                            </a>
                        </div>
                    </div>
                    <div id="aa" class="panel-collapse collapse ">
                        <div class="panel-body">
                            <ul class="nav nav-pills nav-stacked">
                                <li>
                                    <a href="#"
                                       style="font-weight: bold">管理员列表
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--右边-->
        <div class="col-xs-10" id="centerLayout">
            <!--巨幕-->
            <div class="jumbotron">
                <h2 style="color:#898080;">欢迎来到持名法州后台管理系统</h2>
            </div>
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

                <div class="carousel-inner" role="listbox">
                    <div class="item active">
                        <img src="{% static 'img/shouye.jpg' %}" alt="..." style="height: 60%;width: auto">
                        <div class="carousel-caption">
                            ...
                        </div>
                    </div>
                    <div class="item">
                        <img src="{% static 'img/shouye.jpg' %}" alt="..." style="height: 60%;width: auto">
                        <div class="carousel-caption">
                        </div>
                    </div>
                    <div class="item">
                        <img src="{% static 'img/shouye.jpg' %}" alt="..." style="height: 60%;width: auto">
                        <div class="carousel-caption">
                        </div>
                    </div>
                </div>
                <!-- Controls -->
                <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

        </div>
    </div>
</div>
<br/>
<div class="panel-footer">
    <div class="panel-title">
        <h5 style="text-align: center">@百知教育 pang_shanshan@sina.com</h5>
    </div>
</div>


</body>
</html>

templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static '/boot/css/bootstrap.min.css' %}">
    <script type="text/javascript" src="{% static '/boot/js/jquery-2.2.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'boot/js/bootstrap.min.js' %}"></script>
    <script>
        var countdown = 60;
        function settime(obj) {
            if (countdown == 0) {
                obj.removeAttribute("disabled");
                obj.value = "免费获取验证码";
                countdown = 60;
                return;
            } else {
                obj.setAttribute("disabled", true);
                obj.value = "重新发送(" + countdown + ")";
                countdown--;
            }
            setTimeout(function () {
                    settime(obj)
                }
                , 1000)
        }
        $(function () {
            $('#getcode').click(function () {
                var mobile = $('#inputphone').val();
                $.ajax({
                    url:"{% url 'pss_show:getcode' %}",
                    type:"post",
                    data:"mobile="+ mobile,
                    success:function (resp) {
                        console.log(resp);
                        if(resp==="手机号格式不正确"){
                            alert("手机号输入有误，请重新输入")
                        }else if(resp==="发送频繁稍后重试"){
                            alert("操作过于频繁，请稍后再试")
                        }
                    }
                });
            });
            $('#loginButtonId').click(function () {
                var mobile = $('#inputphone').val();
                var code = $('#code').val();
                var username = $('#username').val();
                console.log(code);
                $.ajax({
                    url:"{% url 'pss_show:loginlogic' %}",
                    type:"post",
                    data:"mobile="+ mobile+"&code="+code+"&username="+username,
                    success:function (resp) {
                        console.log(resp);
                        if(resp ==="验证码输入错误"){
                            alert("验证码输入错误,请重新输入")
                        }else if(resp === "验证码过期"){
                            alert("验证码过期,请重新获取")
                        }else if(resp === "用户名错误"){
                            alert("没有查询到此用户名，请重试")
                        }else if(resp === "ok"){
                            window.location.href = '{% url "pss_show:index" %}'
                        }
                    }
                })
            })
        })
    </script>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2">
            <form action="" class="form-horizontal">
                <div class="form-group">
                    <label for="inputphone">手机号</label>
                    <div class="input-group">
                        <input type="text" id="inputphone" class="form-control" placeholder="请输入手机号">
                        <span class="input-group-btn">
                            <input type="button" id="getcode" onclick="settime(this)" value="免费获取验证码"
                                class="btn btn-success">
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="username">用户名</label>
                    <input type="text" id="username" class="form-control" placeholder="请输入用户名">
                </div>
                <div class="form-group">
                    <label for="code">验证码</label>
                    <input type="text" id="code" class="form-control" placeholder="请输入验证码">
                </div>

                <input class="btn btn-success" type="button" id="loginButtonId" value="登录">
            </form>
        </div>
    </div>
</div>

</body>
</html>

templates/rbac_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<script>

</script>
<form action="/rbac/check_user/" method="post">
    {% csrf_token %}
    用户名：<input type="text" name="name"> <br>
    密码：<input type="text" name="pwd"> <br>
    <input type="submit" value="提交"> <br>
</form>

</body>
</html>